/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedSolicitarMaterialRouteImport } from './routes/_authenticated/solicitar-material'
import { Route as AuthenticatedPesquisarRouteImport } from './routes/_authenticated/pesquisar'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMinhasSolicitacoesRouteImport } from './routes/_authenticated/minhas-solicitacoes'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMarcasIndexRouteImport } from './routes/_authenticated/marcas.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedModelosSlugRouteImport } from './routes/_authenticated/modelos.$slug'
import { Route as AuthenticatedMarcasSlugRouteImport } from './routes/_authenticated/marcas.$slug'
import { Route as AuthenticatedManuaisIdRouteImport } from './routes/_authenticated/manuais.$id'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as AuthenticatedAdminSolicitacoesRouteImport } from './routes/_authenticated/admin.solicitacoes'
import { Route as AuthenticatedAdminManuaisRouteImport } from './routes/_authenticated/admin.manuais'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as ApiPublicWebhooksLastlinkRouteImport } from './routes/api/public/webhooks/lastlink'
import { Route as ApiPublicDownloadsManualIdRouteImport } from './routes/api/public/downloads.$manualId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitarMaterialRoute =
  AuthenticatedSolicitarMaterialRouteImport.update({
    id: '/solicitar-material',
    path: '/solicitar-material',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPesquisarRoute = AuthenticatedPesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhasSolicitacoesRoute =
  AuthenticatedMinhasSolicitacoesRouteImport.update({
    id: '/minhas-solicitacoes',
    path: '/minhas-solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarcasIndexRoute =
  AuthenticatedMarcasIndexRouteImport.update({
    id: '/marcas/',
    path: '/marcas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedModelosSlugRoute =
  AuthenticatedModelosSlugRouteImport.update({
    id: '/modelos/$slug',
    path: '/modelos/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarcasSlugRoute = AuthenticatedMarcasSlugRouteImport.update({
  id: '/marcas/$slug',
  path: '/marcas/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManuaisIdRoute = AuthenticatedManuaisIdRouteImport.update({
  id: '/manuais/$id',
  path: '/manuais/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSolicitacoesRoute =
  AuthenticatedAdminSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminManuaisRoute =
  AuthenticatedAdminManuaisRouteImport.update({
    id: '/manuais',
    path: '/manuais',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicWebhooksLastlinkRoute =
  ApiPublicWebhooksLastlinkRouteImport.update({
    id: '/api/public/webhooks/lastlink',
    path: '/api/public/webhooks/lastlink',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDownloadsManualIdRoute =
  ApiPublicDownloadsManualIdRouteImport.update({
    id: '/api/public/downloads/$manualId',
    path: '/api/public/downloads/$manualId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pesquisar': typeof AuthenticatedPesquisarRoute
  '/solicitar-material': typeof AuthenticatedSolicitarMaterialRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/manuais': typeof AuthenticatedAdminManuaisRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/manuais/$id': typeof AuthenticatedManuaisIdRoute
  '/marcas/$slug': typeof AuthenticatedMarcasSlugRoute
  '/modelos/$slug': typeof AuthenticatedModelosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/marcas/': typeof AuthenticatedMarcasIndexRoute
  '/api/public/downloads/$manualId': typeof ApiPublicDownloadsManualIdRoute
  '/api/public/webhooks/lastlink': typeof ApiPublicWebhooksLastlinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/pesquisar': typeof AuthenticatedPesquisarRoute
  '/solicitar-material': typeof AuthenticatedSolicitarMaterialRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/manuais': typeof AuthenticatedAdminManuaisRoute
  '/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/manuais/$id': typeof AuthenticatedManuaisIdRoute
  '/marcas/$slug': typeof AuthenticatedMarcasSlugRoute
  '/modelos/$slug': typeof AuthenticatedModelosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/marcas': typeof AuthenticatedMarcasIndexRoute
  '/api/public/downloads/$manualId': typeof ApiPublicDownloadsManualIdRoute
  '/api/public/webhooks/lastlink': typeof ApiPublicWebhooksLastlinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/minhas-solicitacoes': typeof AuthenticatedMinhasSolicitacoesRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/pesquisar': typeof AuthenticatedPesquisarRoute
  '/_authenticated/solicitar-material': typeof AuthenticatedSolicitarMaterialRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/manuais': typeof AuthenticatedAdminManuaisRoute
  '/_authenticated/admin/solicitacoes': typeof AuthenticatedAdminSolicitacoesRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/manuais/$id': typeof AuthenticatedManuaisIdRoute
  '/_authenticated/marcas/$slug': typeof AuthenticatedMarcasSlugRoute
  '/_authenticated/modelos/$slug': typeof AuthenticatedModelosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/marcas/': typeof AuthenticatedMarcasIndexRoute
  '/api/public/downloads/$manualId': typeof ApiPublicDownloadsManualIdRoute
  '/api/public/webhooks/lastlink': typeof ApiPublicWebhooksLastlinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/assinatura'
    | '/dashboard'
    | '/favoritos'
    | '/historico'
    | '/minhas-solicitacoes'
    | '/notificacoes'
    | '/perfil'
    | '/pesquisar'
    | '/solicitar-material'
    | '/suporte'
    | '/admin/logs'
    | '/admin/manuais'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/manuais/$id'
    | '/marcas/$slug'
    | '/modelos/$slug'
    | '/admin/'
    | '/marcas/'
    | '/api/public/downloads/$manualId'
    | '/api/public/webhooks/lastlink'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/assinatura'
    | '/dashboard'
    | '/favoritos'
    | '/historico'
    | '/minhas-solicitacoes'
    | '/notificacoes'
    | '/perfil'
    | '/pesquisar'
    | '/solicitar-material'
    | '/suporte'
    | '/admin/logs'
    | '/admin/manuais'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/manuais/$id'
    | '/marcas/$slug'
    | '/modelos/$slug'
    | '/admin'
    | '/marcas'
    | '/api/public/downloads/$manualId'
    | '/api/public/webhooks/lastlink'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/planos'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/assinatura'
    | '/_authenticated/dashboard'
    | '/_authenticated/favoritos'
    | '/_authenticated/historico'
    | '/_authenticated/minhas-solicitacoes'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/pesquisar'
    | '/_authenticated/solicitar-material'
    | '/_authenticated/suporte'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/manuais'
    | '/_authenticated/admin/solicitacoes'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/manuais/$id'
    | '/_authenticated/marcas/$slug'
    | '/_authenticated/modelos/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/marcas/'
    | '/api/public/downloads/$manualId'
    | '/api/public/webhooks/lastlink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicDownloadsManualIdRoute: typeof ApiPublicDownloadsManualIdRoute
  ApiPublicWebhooksLastlinkRoute: typeof ApiPublicWebhooksLastlinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitar-material': {
      id: '/_authenticated/solicitar-material'
      path: '/solicitar-material'
      fullPath: '/solicitar-material'
      preLoaderRoute: typeof AuthenticatedSolicitarMaterialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisar': {
      id: '/_authenticated/pesquisar'
      path: '/pesquisar'
      fullPath: '/pesquisar'
      preLoaderRoute: typeof AuthenticatedPesquisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-solicitacoes': {
      id: '/_authenticated/minhas-solicitacoes'
      path: '/minhas-solicitacoes'
      fullPath: '/minhas-solicitacoes'
      preLoaderRoute: typeof AuthenticatedMinhasSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marcas/': {
      id: '/_authenticated/marcas/'
      path: '/marcas'
      fullPath: '/marcas/'
      preLoaderRoute: typeof AuthenticatedMarcasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/modelos/$slug': {
      id: '/_authenticated/modelos/$slug'
      path: '/modelos/$slug'
      fullPath: '/modelos/$slug'
      preLoaderRoute: typeof AuthenticatedModelosSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marcas/$slug': {
      id: '/_authenticated/marcas/$slug'
      path: '/marcas/$slug'
      fullPath: '/marcas/$slug'
      preLoaderRoute: typeof AuthenticatedMarcasSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manuais/$id': {
      id: '/_authenticated/manuais/$id'
      path: '/manuais/$id'
      fullPath: '/manuais/$id'
      preLoaderRoute: typeof AuthenticatedManuaisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/solicitacoes': {
      id: '/_authenticated/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AuthenticatedAdminSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/manuais': {
      id: '/_authenticated/admin/manuais'
      path: '/manuais'
      fullPath: '/admin/manuais'
      preLoaderRoute: typeof AuthenticatedAdminManuaisRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/lastlink': {
      id: '/api/public/webhooks/lastlink'
      path: '/api/public/webhooks/lastlink'
      fullPath: '/api/public/webhooks/lastlink'
      preLoaderRoute: typeof ApiPublicWebhooksLastlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/downloads/$manualId': {
      id: '/api/public/downloads/$manualId'
      path: '/api/public/downloads/$manualId'
      fullPath: '/api/public/downloads/$manualId'
      preLoaderRoute: typeof ApiPublicDownloadsManualIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminManuaisRoute: typeof AuthenticatedAdminManuaisRoute
  AuthenticatedAdminSolicitacoesRoute: typeof AuthenticatedAdminSolicitacoesRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminManuaisRoute: AuthenticatedAdminManuaisRoute,
  AuthenticatedAdminSolicitacoesRoute: AuthenticatedAdminSolicitacoesRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedMinhasSolicitacoesRoute: typeof AuthenticatedMinhasSolicitacoesRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPesquisarRoute: typeof AuthenticatedPesquisarRoute
  AuthenticatedSolicitarMaterialRoute: typeof AuthenticatedSolicitarMaterialRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedManuaisIdRoute: typeof AuthenticatedManuaisIdRoute
  AuthenticatedMarcasSlugRoute: typeof AuthenticatedMarcasSlugRoute
  AuthenticatedModelosSlugRoute: typeof AuthenticatedModelosSlugRoute
  AuthenticatedMarcasIndexRoute: typeof AuthenticatedMarcasIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedMinhasSolicitacoesRoute: AuthenticatedMinhasSolicitacoesRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPesquisarRoute: AuthenticatedPesquisarRoute,
  AuthenticatedSolicitarMaterialRoute: AuthenticatedSolicitarMaterialRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedManuaisIdRoute: AuthenticatedManuaisIdRoute,
  AuthenticatedMarcasSlugRoute: AuthenticatedMarcasSlugRoute,
  AuthenticatedModelosSlugRoute: AuthenticatedModelosSlugRoute,
  AuthenticatedMarcasIndexRoute: AuthenticatedMarcasIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicDownloadsManualIdRoute: ApiPublicDownloadsManualIdRoute,
  ApiPublicWebhooksLastlinkRoute: ApiPublicWebhooksLastlinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
